import Head from 'next/head'
import Image from 'next/image'

import { Inter } from '@next/font/google'
import Footer from '../components/Footer'
import { useState } from 'react'
import ProtectedPage from '../components/util/ProtectedPage'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const [showDownload1, setShowDownload1] = useState(false)
  const [showDownload2, setShowDownload2] = useState(false)
  const [showPdf, setShowPdf] = useState(1)
  // const isMobile = useMediaQuery('(max-width: 768px)')
  
  const debug = false

  return (
    <ProtectedPage>
      <Head>
        <title>Cabinets Southwest Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
      <div className='col col-md-6 mx-auto position-relative mb-5 mx-auto mt-5' style={{minHeight:"100px"}}>
        <Image
          src={'/swc_logo_final_color.webp'}
          alt="logo"
          objectFit={'contain'}
          fill 
        />  
      </div>
     
      <hr/>



      <div className='mb-5 d-flex flex-column justify-content-center text-center'>
        <h2>Admin Page</h2>
       
      </div>
      <hr/>

      </main>
    </ProtectedPage>
  )
}
