import Head from 'next/head'
import Image from 'next/image'

import { Inter } from '@next/font/google'
import Footer from '../components/Footer'
import { useState } from 'react'
import ProtectedPage from '../components/util/ProtectedPage'
import { signOut } from 'next-auth/react'
import Navbar from '../components/Navbar'
const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  
  const logOut = () =>{
    localStorage.removeItem("admin")
    localStorage.removeItem("potentialAdmin")

    signOut({callbackUrl:"/"})
  }

  return (
    <ProtectedPage>
      <Head>
        <title>Cabinets Southwest Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
     
      <div className='col col-md-6 mx-auto position-relative mb-5 mx-auto mt-5 text-center' style={{minHeight:"100px"}}>
        <Image
            src={'/swc_logo_final_color.webp'}
            alt="logo"
            objectFit={'contain'}
            width = {256}
            height = {100} 
          />  
      </div>
     
      
      <Navbar/>

      <h2 className='text-center mt-4'>Admin Page</h2>
        <div className='container'>
            <div className='mb-5 d-flex flex-column justify-content-center text-center'>
            
            <div className='border d-flex mt-3 flex-column col-lg-6 col-12 mx-auto bg-info'>

                <h4 className='mt-4 mb-4'>Important Links</h4>
                <div className='p-sm-5 p-2 bg-light '>
                  <DescriptionLink
                    description = "View your web traffic and other insights"
                    linkText = "Google Analytics"
                    href = "https://analytics.google.com/"
                  />
                  <hr/>
                  <DescriptionLink
                    description = "Modify your downloadable documents"
                    linkText = "Google Docs"
                    href = "https://docs.google.com/"
                  />
                  <hr/>
                  <DescriptionLink
                    description = "Modify the code (i.e. website text)"
                    linkText = "GitHub"
                    href = "https://github.com/"
                  />
                  <hr/>
                  <DescriptionLink
                    description = "Deploy New Site Changes"
                    linkText = "Digital Oceans"
                    href = "https://cloud.digitalocean.com/login"
                  />

                </div>

                

              
            </div>

        </div>
        <hr/>
        </div>

      

        <Footer/>
      </main>
    </ProtectedPage>
  )
}

const DescriptionLink = (props) => {
  return(
    <div className={'flex-lg-row flex-column d-flex '+props.className}>
      <a className='col-lg-5 col-12 btn btn-secondary d-flex justify-content-center align-items-center py-2' target = {"_blank"} href = {props.href}>{props.linkText}</a>
      <p className='col-lg-7 col-12 ms-lg-3 mt-lg-0 mt-3 col-lg-8 mb-0 align-self-center text-lg-start text-center'>{props.description}</p>
    </div>
  )
}